# Generated by Django 5.2.4 on 2025-07-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=50)),
                ('cliente_fornecedor', models.CharField(blank=True, max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('valor', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('forma_pagamento', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
